### ISSUE TITLE
Port for React Native 

### ISSUE THREAD

**Issue by rvuyyuru1** [CRED-CLUB/neopop-web#1]
Please provide support for react native as well

**Comment by mittalchirag** [comment]
hey, @rvuyyuru1 
react-native is not yet in our roadmap. 
but we will surely love if someone picks up and port it to react-native. 🙂 
thanks.

**Comment by efoken** [comment]
I'm on it https://github.com/efoken/neopop-react-native

Already ported the most stuff to React Native, also with Web support and everything tested in Storybook 😄

**Comment by rvuyyuru1** [comment]
@efoken great to hear

**Comment by n1shantvarma** [comment]
hey @mittalchirag , any support for react-native?
