### ISSUE TITLE
Fonts broken in Storybook

### ISSUE THREAD

**Issue by satyajitghana** [CRED-CLUB/neopop-web#4]
Most of the storybook examples have broken font (defaults to Times), is that intentional?

<img width="436" alt="image" src="https://user-images.githubusercontent.com/8092481/177526763-718e9de4-bc79-49cb-84c0-0b4f0054e0f4.png">

**Comment by satyajitghana** [comment]
@mittalchirag do something

**Comment by rahuldkjain** [comment]
Yeah, this is intentional.
